
const ques = [
    {lang:'en',msg:'goodbye for now',type:'greetings.bye'},
    {lang:'en',msg:'okay see you later',type:'greetings.bye'},
    {lang:'en',msg:'bye for now',type:'greetings.bye'},
    {lang:'en',msg:'i must go',type:'greetings.bye'},
    {lang:'en',msg:'hello',type:'greetings.hello'},
    {lang:'en',msg:'hi',type:'greetings.hello'},
    {lang:'en',msg:'howdy',type:'greetings.hello'},
    {lang:'en',msg:'hey',type:'greetings.hello'},
    {lang:'en',msg:'who are you?',type:'bot.info'},
    {lang:'en',msg:'who created you',type:'bot.creator'},
    {lang:'en',msg:'how old are you?',type:'bot.age'},
    {lang:'en',msg:'where are you from?',type:'bot.from'},
    {lang:'en',msg:'Just browsing!',type:'landing.just'},
    {lang:'en',msg:"I'd like to learn more about Bitmify",type:'landing.learn'},
    {lang:'en',msg:"I'm a BusiBit customer with a question",type:'landing.quest'},
    {lang:'en',msg:'asshole',type:'inappropriate'},
    {lang:'en',msg:'fuck',type:'inappropriate'},
    {lang:'en',msg:'fuck you',type:'inappropriate'},
    {lang:'en',msg:'gay',type:'inappropriate'},
    {lang:'en',msg:'dick',type:'inappropriate'},
    {lang:'en',msg:'pussy',type:'inappropriate'},
    {lang:'en',msg:'ass',type:'inappropriate'},
    {lang:'en',msg:'butt',type:'inappropriate'},
    {lang:'en',msg:'bitch',type:'inappropriate'},
]

const answ = [
    {lang:'en',msg:'Till next time',type:'greetings.bye'},
    {lang:'en',msg:'see you soon!',type:'greetings.bye'},
    {lang:'en',msg:'see you later!',type:'greetings.bye'},
    {lang:'en',msg:'Hey there!',type:'greetings.hello'},
    {lang:'en',msg:'Greetings!',type:'greetings.hello'},
    {lang:'en',msg:"Hey, what's up?",type:'greetings.hello'},
    {lang:'en',msg:'I am a bot created by <b>Eduardo Ruiz</b>, a Full Stack Developer.',type:'bot.info'},
    {lang:'en',msg:'I was created by <b>Eduardo Ruiz | Full Stack Developer</b>',type:'bot.creator'},
    {lang:'en',msg:"I'm a baby bot, I'm barely 2 years old :)",type:'bot.age'},
    {lang:'en',msg:'I was created in Venezuela',type:'bot.from'},
    {lang:'en',msg:'Amazing, feel free to browse all sections of our website.',type:'landing.just'},
    {lang:'en',msg:'<b>Bitmify</b> is a website for the exchange of cryptocurrencies, through P2P transactions in real time, we make the process so easy that even a child can understand.',type:'landing.learn'},
    {lang:'en',msg:'Excellent, I am here to answer all your questions.',type:'landing.quest'},
    {lang:'en',msg:"I'm just a kid :'(",type:'inappropriate'},
    {lang:'en',msg:"I'm a decent bot, I don't like rudeness.",type:'inappropriate'},
    {lang:'en',msg:'please stop :(',type:'inappropriate'},
    {lang:'en',msg:'bullying is bad :(',type:'inappropriate'},
]
module.exports = {ques, answ}